language: node_js
node_js:
  - "5.0"

branches:
  only:
    - master

before_script:
  - npm install -g gulp
script: gulp test
after_script:
  - gulp coveralls

# required to get bcrypt to build
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

env:
  - CXX=g++-4.8